# Points schema

# --- !Ups

CREATE TABLE FACULTY (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  NAME TEXT NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE GROUPS (
  ID        BIGINT NOT NULL AUTO_INCREMENT,
  GROUPNAME TEXT   NOT NULL,
  FACULTYID BIGINT NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE TEACHERS (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  NAME TEXT NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE SUBJECTS (
  ID         BIGINT NOT NULL AUTO_INCREMENT,
  NAME       TEXT   NOT NULL,
  GROUPID    LONG   NOT NULL,
  FACULTYID  LONG   NOT NULL,
  TEACHERID  LONG,
  DAY        TEXT   NOT NULL,
  START      TIME   NOT NULL,
  ODDNOT     BOOL   NOT NULL,
  KIND       TEXT   NOT NULL,
  auditorium INTEGER,
  PRIMARY KEY (ID)
);

# --- !Downs

DROP TABLE FACULTY;
DROP TABLE GROUPS;
DROP TABLE TEACHERS;
DROP TABLE SUBJECTS;